version: '3.2'

networks:
  enovateurs-network:
    driver: bridge
services:
  enovateurs-web:
    image: php:rc-apache
    networks:
      - enovateurs-network
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./www/
        target: /var/www/html
